# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
# Conforming Agent Chart Header
# This is a YAML-formatted file.
apiVersion: v2
name: conforming-agent
description: >-
  Tractus-X Conforming Agent - Knowledge-Agents Testing Module
home: https://github.com/eclipse-tractusx/knowledge-agents/main/charts/conforming-agent
type: application
appVersion: "1.9.5-SNAPSHOT"
version: 1.9.5-SNAPSHOT
icon: https://catenax-ng.github.io/product-knowledge/img/agents_kit.svg
maintainers: 
  - name: 'Tractus-X Knowledge Agents Team'
