name: DAST
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  zap_scan:
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    name: OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Copy OpenAPI JSON
        run: cp .github/workflows/openapi_Knowledge_Agents.json $GITHUB_WORKSPACE
        
      - name: ZAP Scan 1
        id: scan1
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://knowledge.dev.demo.catena-x.net'
        env:
          DEBUG: 'true'
          OPENAPI_FILE: $GITHUB_WORKSPACE/openapi_Knowledge_Agents.json  # Pass the path to the OpenAPI JSON file as an environment variable
