name: DAST
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://managed-identity-wallets.dev.demo.catena-x.net/'
